### PR TITLE
params value can depend on object which fell out of session scope.

### PR DESCRIPTION
**Pull request by maparent**
We had many DetachedInstanceErrors when trying to use sqltap with pyramid. Ideally we should capture values earlier, but this is a temporary workaround.

### CODE REVIEW

**Comment by inconshreveable** [comment]
Thanks for the fix! 

I agree, the 'correct' fix is for sqltap to copy the values earlier to make sure that this doesn't happen.

Two things:

1. Can we catch the specific exception so that we don't mask other potential problems?
2. Can we get a test for this?
3. Let's add a comment that this is a temporary workaround and link to this thread.

**Comment by maparent** [comment]
Specific exception and comment written.
Testing may take longer to write, it will not happen today. 
When I get around to it, would you want me to test the mako template directly or through the middleware?

**Comment by maparent** [comment]
Another comment: even earlier capture does not guarantee that it will never happen, it just makes it much less likely.

**Comment by inconshreveable** [comment]
mmmm good question. let's test the template for now since that's where the new code is.

in what case will immediate capture not protect against a detactedinstanceerror?

**Comment by maparent** [comment]
hmm.... let's just say I have many cases of those, so I expect them everywhere; but I now realize that your main hook is before_execute, which should be fine. OK, you can scratch my last comment.

**Pull request closed without merging**
