### PR TITLE
Fix issue when iterating over the query parameters

### PR DESCRIPTION
**Pull request by Daniel-Brosnan-Blazquez**
Description of the issue can be found here:
https://github.com/inconshreveable/sqltap/issues/38

### CODE REVIEW

**Comment by Daniel-Brosnan-Blazquez** [comment]
Sorry for the delay. Ok, I will try to generate a test but it is going to take me a while as I will have to study better the code and find the time to do it. At first, I saw the workaround but not fully understand what is the root cause of the issue. I was expecting some challenging from you actually, but I will try to help on that.
Thanks a lot for your feedback.

**Comment by inconshreveable** [comment]
yeah, i'm hoping that being able to write a test will get us to understand the root cause of the issue (does that sound right?)

**Comment by Daniel-Brosnan-Blazquez** [comment]
Sorry Alan, it seems that pip3 installs an older version and when I checked the change I changed both the template of the installed package and the template of the project. Tests were successful and the generation was also successful. But, if I execute the code with the latest code on github the error does not occur either. This is because it has been corrected:
- Code I was using, installed by pip3:
```html
                    % for param_name in params:
                    <td>${query.params[param_name]}</td>
                    % endfor
```
- Code of the latest version
```html
                    % for param_name in params:
                    <td>${query.params.get(param_name, '')}</td>
                    % endfor
```
So, actually if the line is changed to the older version, several tests fail:
- test_sqltap.TestSQLTapMiddleware.test_report_aggregation_w_different_param_sets
- test_sqltap.TestSQLTap.test_report_aggregation_w_different_param_sets
Sorry for the noise, you can reject the merge.

**Comment by inconshreveable** [comment]
Ahh, thank you for checking? so what you're saying is that the latest code needs to get published to pypi, is that correct?

**Comment by Daniel-Brosnan-Blazquez** [comment]
At least the package installed by pip in my ubuntu 14.04 was not containing the latest version. But it could be that for newer versions of ubuntu pip is installing the latest version. Have you checked?

**Pull request closed without merging**
