### PR TITLE
Implement sqltap text reporter

### PR DESCRIPTION
**Pull request by stanzgy**
* fix two bugs including #17 
* add Reporter class so we could get various ways to do a sqltap report.
* add TextReporter and text.mako template to generate text report
* refact sqltap.report() so we can make html/wsgi/text report now
* sqltap.report() testcases updated

### CODE REVIEW

**Comment by stanzgy** [comment]
Text report test script:
```
from sqlalchemy import *

import sqltap

if __name__ == '__main__':

    engine = create_engine('sqlite://')

    m1 = MetaData(engine)
    t1 = Table("sometable", m1,
            Column("id", Integer, primary_key=True),
            Column("data", String(255), nullable=False))

    conn = engine.connect()
    m1.create_all(conn)

    profiler = sqltap.start()

    conn.execute(
        t1.insert(),
        [{"data": "entry %d" % x} for x in xrange(100000)]
    )

    conn.execute(
        t1.select().where(t1.c.data.between("entry 25", "entry 7800")).order_by(desc(t1.c.data))
    )
    conn.execute(
        t1.select().where(t1.c.data.between("entry 25", "entry 7800")).order_by(desc(t1.c.data))
    )
    conn.execute(
        t1.select().where(t1.c.data.between("entry 300", "entry 7800")).order_by(desc(t1.c.data))
    )


    stat = profiler.collect()
    sqltap.report(stat, "report.txt", report_format="text")
```

sample result:
```

========================================================================
======                  SQLTap Profiling Report                   ======
========================================================================
Report Generated Time: 2015-05-24 21:18:12.727911

========================================================================
======                          Summary                           ======
========================================================================
Total queries: 4
Total time: 0.57 second(s)

========================================================================
======                          Details                           ======
========================================================================

============                  QueryGroup 0                  ============
------------              QueryGroup 0 summary              ------------
Query count: 1
Query max time: 0.468 second(s)
Query min time: 0.468 second(s)
Query mean time: 0.468 second(s)
Query median time: 0.468 second(s)

------------            QueryGroup 0 SQL pattern            ------------
INSERT INTO sometable (id, data)
VALUES (?,
        ?)

------------             QueryGroup 0 breakdown             ------------
Query 0:
  Query duration: 0.468 second(s)
  Query params:
    data: None
    id: None

------------              QueryGroup 0 stacks               ------------
Total unique stack(s) issued this QueryGroup: 1


Stack 0:
  1 call(s) from <module> @sqlt.py:21
  Traceback:
      File "sqlt.py", line 21, in <module>
        [{"data": "entry %d" % x} for x in xrange(100000)]
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1014, in _execute_clauseelement
        elem, multiparams, params, ret)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 258, in __call__
        fn(*args, **kw)

============                  QueryGroup 1                  ============
------------              QueryGroup 1 summary              ------------
Query count: 3
Query max time: 0.037 second(s)
Query min time: 0.032 second(s)
Query mean time: 0.034 second(s)
Query median time: 0.033 second(s)

------------            QueryGroup 1 SQL pattern            ------------
SELECT sometable.id,
       sometable.data
FROM sometable
WHERE sometable.data BETWEEN ? AND ?
ORDER BY sometable.data DESC

------------             QueryGroup 1 breakdown             ------------
Query 0:
  Query duration: 0.032 second(s)
  Query params:
    data_2: entry 7800
    data_1: entry 300
Query 1:
  Query duration: 0.037 second(s)
  Query params:
    data_2: entry 7800
    data_1: entry 25
Query 2:
  Query duration: 0.033 second(s)
  Query params:
    data_2: entry 7800
    data_1: entry 25

------------              QueryGroup 1 stacks               ------------
Total unique stack(s) issued this QueryGroup: 3


Stack 0:
  1 call(s) from <module> @sqlt.py:31
  Traceback:
      File "sqlt.py", line 31, in <module>
        t1.select().where(t1.c.data.between("entry 300", "entry 7800")).order_by(desc(t1.c.data))
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1014, in _execute_clauseelement
        elem, multiparams, params, ret)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 258, in __call__
        fn(*args, **kw)

Stack 1:
  1 call(s) from <module> @sqlt.py:28
  Traceback:
      File "sqlt.py", line 28, in <module>
        t1.select().where(t1.c.data.between("entry 25", "entry 7800")).order_by(desc(t1.c.data))
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1014, in _execute_clauseelement
        elem, multiparams, params, ret)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 258, in __call__
        fn(*args, **kw)

Stack 2:
  1 call(s) from <module> @sqlt.py:25
  Traceback:
      File "sqlt.py", line 25, in <module>
        t1.select().where(t1.c.data.between("entry 25", "entry 7800")).order_by(desc(t1.c.data))
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1014, in _execute_clauseelement
        elem, multiparams, params, ret)
      File "/Users/stanzgy/workspace/openstack/devscripts/sql/.venv/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 258, in __call__
        fn(*args, **kw)

```

**Comment by inconshreveable** [comment]
Awesome, here are my thoughts:

1. It looks like the template parameter is being removed from 'report()' which would be a breaking change to the API, and I don't think we should make breaking changes to the API.
2. There is a new dependency on the 'sqlparse' module which needs to be pinned to a specific version.
3. There seems to be a lot of code copy/pasted between the HTMLReporter and TextReporter, is there a way to factor that out? Is there any difference in the code used for those two different reporters?
4. Instead of renaming the filename paramter to 'report_file', I would recommend we just deprecate the 'filename' parameter entirely. It's mixing concerns to have the report function also write things to files. It should just generate reports.

Would it make more sense instead to leave the report() function unchanged and instead add a new API on top which would return the appropriate template file to use for generating the report?

Thoughts?

**Comment by stanzgy** [comment]
On Sun, May 31, 2015 at 12:40 PM, Alan Shreve <notifications@github.com>
wrote:

> Awesome, here are my thoughts:
>
>    1. It looks like the template parameter is being removed from
>    'report()' which would be a breaking change to the API, and I don't think
>    we should make breaking changes to the API.
>
> Okay, I'll add this back.

>
>    1. There is a new dependency on the 'sqlparse' module which needs to
>    be pinned to a specific version.
>
> Okay. Generally I intend to use this 'sqlparse' to pretty print the sql
query text without any its advanced usage, since sometimes the sql gets too
long and complex to see under text format. Addtionally I'll add 'try
except' around the 'sql.format' and if it failed we just print the original
raw sql text.

>
>    1. There seems to be a lot of code copy/pasted between the
>    HTMLReporter and TextReporter, is there a way to factor that out? Is there
>    any difference in the code used for those two different reporters?
>
> Yeah, the main difference is the the template filter flag (['unicode',
'h'] against ['unicode']) and the report_file open flag ('w' against 'a').
I shall refactor this.

>
>    1. Instead of renaming the filename paramter to 'report_file', I would
>    recommend we just deprecate the 'filename' parameter entirely. It's mixing
>    concerns to have the report function also write things to files. It should
>    just generate reports.
>
> You mean we will just generate the report but not write it to files
anymore in future. Is it right?

>
>
> Would it make more sense instead to leave the report() function unchanged
> and instead add a new API on top which would return the appropriate
> template file to use for generating the report?
>
> Thoughts?
>
 Not very clear about this, could give a simple example to illustate?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inconshreveable/sqltap/pull/20#issuecomment-107127199>
> .
>



-- 
Best Regards,

Zhang Gengyuan

**Comment by inconshreveable** [comment]
Okay that all sounds good.

"You mean we will just generate the report but not write it to files anymore in the future". Right. I mean we should just leave the parameter there but mark it deprecated. Don't add a new 'report_file' argument.

Let's not worry about API design right now. There's a lot of really good code in here that I'd rather get merged and we can worry about tweaking the API in a future revision.

**Comment by stanzgy** [comment]
hi Alan, I pushed new commits and you can check it now.

On Sat, Jun 6, 2015 at 4:23 AM, Alan Shreve <notifications@github.com>
wrote:

> Okay that all sounds good.
>
> "You mean we will just generate the report but not write it to files
> anymore in the future". Right. I mean we should just leave the parameter
> there but mark it deprecated. Don't add a new 'report_file' argument.
>
> Let's not worry about API design right now. There's a lot of really good
> code in here that I'd rather get merged and we can worry about tweaking the
> API in a future revision.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inconshreveable/sqltap/pull/20#issuecomment-109429710>
> .
>



-- 
Best Regards,

Zhang Gengyuan

**Comment by inconshreveable** [comment]
Sorry it took me so long to get this merged in! Thank you so much for the contribution and making sqltap better, this was a truly awesome addition!

**Comment by inconshreveable** [comment]
Uploaded as version 0.3.9

**Pull request merged**
